module.exports = function() {
    var client = './src/client/';
    var clientApp = client + 'app/';
    var report = './report/';
    var temp = './.tmp/';
    var server = './src/server/';
    var root = './';

    return {
        alljs        : [
            './src/**/*.js',
            './*.js',
            '!./src/**/*spec.js',
            '!./karma.conf.js'
        ],
        build        : './build/',
        client       : client,
        css          : temp + 'styles.css',
        fonts        : [client + 'fonts/**/*.*'],
        html         : clientApp + '**/*.html',
        htmltemplates: clientApp + '**/*.html',
        images       : client + 'images/**/*.*',
        index        : client + 'index.html',
        js                : [
            clientApp + '**/*.module.js',
            clientApp + '**/*.js',
            '!' + clientApp + '**/*spec.js'
        ],
        sass              : client + '**/*.scss',
        report            : report,
        root              : root,
        server            : server,
        temp              : temp,
        /**
         * optimized files
         */
        optimized         : {
            app      : 'app.js',
            lib      : 'lib.js',

            bowerCss: 'library.css',
            bowerJs : 'library.js',

            appDev: 'xxxTemplatexxx.js',
            cssDev: 'xxxTemplatexxx.css'
        },
        /**
         * template cache
         */
        templateCache     : {
            file   : 'template.js',
            options: {
                module    : 'xxxTemplatexxx',
                standAlone: false,
                root      : 'app/'
            }
        },
        /**
         * browser sync
         */
        browserReloadDelay: 1000,
        /**
         *Bower and NPM locations
         */
        bower             : {
            json      : require('./bower.json'),
            directory : './bower_components/',
            ignorePath: '../..'
        },
        packages          : [
            './package.json',
            './bower.json'
        ],
        defaultPort       : 7777,
        nodeServer        : './src/server/app.js',
        clientApp         : clientApp,
        constantTemplate  :
        '(function () {\n' +
        '    \'use strict\';\n' +
        '    // DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n' +
        '    angular\n' +
        '        .module(\'<%- moduleName %>\')\n' +
        '<% constants.forEach(function(constant) { %>        .constant(\'<%- constant.name %>\', <%= constant.value %>)\n<% }) %>;\n' +
        '})();\n'
    };
};
